routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/Negocios', [App\Http\Controllers\TuristaController::class, 'negocios'])->name('negocios');
Route::get('/Ubicacion', [App\Http\Controllers\TuristaController::class, 'ubicacion'])->name('ubicacion');
Route::get('/about', [App\Http\Controllers\TuristaController::class, 'about'])->name('about');
Route::get('/recorrido-virtual', [App\Http\Controllers\TuristaController::class, 'virtual'])->name('virtual');
Route::post('/encuesta', [App\Http\Controllers\TuristaController::class, 'encuesta'])->name('encuesta.store');

Route::get('/grafica-encuestas', [App\Http\Controllers\HomeController::class, 'grafica']);


// App::missing(function($exception)
// {
//     return Response::view('errors.missing', array(), 404);
// });

Route::group(['middleware' => 'auth'], function() {
    Route::get('/users/create', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');
    Route::post('/users', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');
    Route::get('/users', [App\Http\Controllers\UserController::class, 'index'])->name('users.index');
    Route::get('/users/{user}', [App\Http\Controllers\UserController::class, 'show'])->name('users.show');
    Route::get('/users/{user}/edit', [App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');
    Route::put('/users/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
    Route::delete('/users/{user}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.delete');
    Route::resource('posts', App\Http\Controllers\PostController::class);
    Route::resource('permissions', App\Http\Controllers\PermissionController::class);
    Route::resource('roles', App\Http\Controllers\RoleController::class);

    Route::resource('comercios', App\Http\Controllers\ComercioController::class);
    Route::get('/comercio/{id}edit', [App\Http\Controllers\ComercioController::class, 'edit'])->name('comerciosedit');

    
    Route::get('/negocios', [App\Http\Controllers\NegocioController::class, 'index'])->name('negocios.index');
    Route::get('/negocios/{id}', [App\Http\Controllers\NegocioController::class, 'show'])->name('negocios.show');
    Route::get('/negocios/{id}/edit', [App\Http\Controllers\NegocioController::class, 'edit'])->name('negocios.edit');
    Route::put('/negocios/{id}', [App\Http\Controllers\NegocioController::class, 'update'])->name('negocios.update');
    Route::post('/negocios/file', [App\Http\Controllers\NegocioController::class, 'file'])->name('negocios.file');
   

});

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('img/sidebar-1.jpg') }}">
  <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
  <div class="logo">
    <a href="#" class="simple-text logo-normal">
      {{ __('Administración') }}
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
          <i class="material-icons">dashboard</i>
            <p>{{ __('Home') }}</p>
        </a>
      </li>
  
      @can('user_index')
      <li class="nav-item{{ $activePage == 'users' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('users.index') }}">
          <i class="material-icons">content_paste</i>
            <p>Usuarios</p>
        </a>
      </li>
      @endcan
      @can('user_index')
      <li class="nav-item{{ $activePage == 'language' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('comercios.index') }}">
          <i class="material-icons">language</i>
          <p>{{ __('Comercios') }}</p>
        </a>
      </li>
      @endcan
      @can('permission_index')
      <li class="nav-item{{ $activePage == 'permissions' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('permissions.index') }}">
          <i class="material-icons">bubble_chart</i>
          <p>{{ __('Permissions') }}</p>
        </a>
      </li>
      @endcan
      @can('role_index')
      <li class="nav-item{{ $activePage == 'roles' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('roles.index') }}">
          <i class="material-icons">location_ons</i>
            <p>{{ __('Roles') }}</p>
        </a>
      </li>
      @endcan
      @can('user_boton')
      <li class="nav-item{{ $activePage == 'language' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('negocios.index') }}">
          <i class="material-icons">language</i>
          <p>{{ __('Mi Negocio') }}</p>
        </a>
      </li>
      @endcan
      

     <li class="nav-item dropdown">
          <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons">person</i>
            <!-- <p class="d-lg-none d-md-block">
              {{ __('Cerrar Sesion') }}
            </p> -->
            <p>{{ __('Cerrar Sesion') }}</p>
          </a>
         
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">{{ __('Log out') }}</a>
          </div>
        </li>
    
    </ul>
  </div>
</div>